"""first

Revision ID: 57342b317201
Revises: 
Create Date: 2021-08-24 00:06:03.786742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57342b317201'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beginning', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('PARLAMENTARNI', 'PREDSEDNICKI', name='electiontype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.Enum('PARTIJA', 'POJEDINAC', name='participanttype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jmbg', sa.Integer(), nullable=False),
    sa.Column('idElection', sa.Integer(), nullable=False),
    sa.Column('idParticipant', sa.Integer(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['idElection'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['idParticipant'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('participants')
    op.drop_table('elections')
    # ### end Alembic commands ###
